version: "3"

services:

  yandex-mongo:
    container_name: yandex-mongo
    image: mongo

    ports:
      - "27017:27017"

    env_file:
      - ./.env

    networks:
      - common

  yandex-postgres:
    container_name: yandex-postgres
    image: postgres:12

    volumes:
    - /home/deploy/services/postgres:/var/lib/postgresql/data

    ports:
      - "5432:5432"

    env_file:
      - ./.env

    networks:
      - common

  yandex-pgadmin:
    container_name: yandex-pgadmin
    image: dpage/pgadmin4:4.18

    ports:
      - "8080:80"

    env_file:
      - ./.env

    environment:
      - PGADMIN_LISTEN_PORT=80

    depends_on:
      - yandex-postgres

    networks:
      - common

  game:
    build:
      context: .

    container_name: game
    image: game

    env_file:
      - ./.env

    ports:
      - "5000:5000"

    depends_on:
      - yandex-mongo
      - yandex-postgres

    networks:
      - common


networks:
  common:
    driver: bridge
