name: CI/CD

on:
  push:
    branches: ["main", "sprint_9", "git-hub-actions"]
  pull_request:
    branches: ["main", "sprint_9", "git-hub-actions"]

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - uses: actions/checkout@v3

      - name: Set up node ${{matrix.node-version}}
      - uses: actions/setup-node-@v3
        with:
          node-version: ${{matrix.node-version}}

      - name: install deps
        run: npm ci --legacy-peer-deps

      - name: build to dist folder
        run: npm run build

      - name: deploy to server
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{secrets.SERVER_SSH_KEY}}
          ARGS: "-rltgoDzv0 --delete"
          SOURCE: "dist/"
          REMOTE_HOST: ${{secrets.REMOTE_HOST}}
          REMOTE_USER: ${{secrets.REMOTE_USER}}
          TARGET: ${{secrets.REMOTE_TARGET}}
          EXCLUDE: "/dist/, /node/modules"
