name: CI/CD


on:
  push:
    branches: ["main", "sprint_9", "git-hub-actions"]

  workflow_dispatch:

env:
  MONGO_HOST: yandex-mongo
  MONGO_PORT: 27017
  MONGO_INITDB_ROOT_USERNAME: user
  MONGO_INITDB_ROOT_PASSWORD: password
  MONGO_DB_NAME: game
  POSTGRESQL_HOST: yandex-postgres
  POSTGRESQL_PORT: 5432
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: game
  PGADMIN_DEFAULT_EMAIL: postgres@postgres.com
  PGADMIN_DEFAULT_PASSWORD: postgres

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Set up GitHub Actions
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          check-latest: true

      - name: Install npm dependencies
        run: npm ci --legacy-peer-deps

      - name: run tests
        run: npm run test

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_MONGO_HOST: ${{ env.MONGO_HOST }}
          envkey_MONGO_PORT: ${{ env.MONGO_PORT }}
          envkey_MONGO_INITDB_ROOT_USERNAME: ${{ env.MONGO_INITDB_ROOT_USERNAME }}
          envkey_MONGO_INITDB_ROOT_PASSWORD: ${{ env.MONGO_INITDB_ROOT_PASSWORD }}
          envkey_MONGO_DB_NAME: ${{ env.MONGO_DB_NAME }}
          envkey_POSTGRESQL_HOST: ${{ env.POSTGRESQL_HOST }}
          envkey_POSTGRESQL_PORT: ${{ env.POSTGRESQL_PORT }}
          envkey_POSTGRES_USER: ${{ env.POSTGRES_USER }}
          envkey_POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          envkey_POSTGRES_DB: ${{ env.POSTGRES_DB }}
          envkey_PGADMIN_DEFAULT_EMAIL: ${{ env.PGADMIN_DEFAULT_EMAIL }}
          envkey_PGADMIN_DEFAULT_PASSWORD: ${{ env.PGADMIN_DEFAULT_PASSWORD }}

          directory: .
          file_name: .env
          fail_on_empty: false

      - name: remove dir files
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ${{ secrets.REMOTE_TARGET }}
            rm -rf *

      - name: Deploy to server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "."
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          EXCLUDE: "/dist/, /node_modules/"

      - name: execute remote script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ${{ secrets.REMOTE_TARGET }}
            bash up.sh
